extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-maven
  container: maven
pipelines:
  pullRequest:
    setup:
      steps:
      - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable  
    build:
      steps:
        - sh: skaffold version
          name: skaffold-version
        - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
          name: container-build

  release:
    setup:
      steps:
      - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable  
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only --tag
        name: tag-with-new-version
    build:
      steps:
        - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
          name: container-build
    promote:
      steps:
      - sh: jx step changelog --version v\$(cat VERSION)
        name: changelog


