extends:
  import: classic
  file: maven/pipeline.yaml
pipelines:
  pullRequest:
    setup:
      steps:
      - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable
    build:
      steps:
      - sh: skaffold version
        name: skaffold-version
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --namespace=$APP_NAME-$BRANCH_NAME --dir ../..
          name: jx-preview

  release:
    setup:
      steps:
      - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable
    build:
      steps:
      - sh: skaffold version
        name: skaffold-version
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx step create pr regex --regex "\n.*$APP_NAME\n.*version:\ (?P<version>.*)$$\n" --version v\$(cat ../../VERSION) --files helm/helmfile.yaml --repo https://github.com/favedom-dev/environment-favedom-dev-staging.git
          #sh: jx step create pr regex --regex "\n.*$APP_NAME\n.*version:\ (?P<version>.*)$$\n" --version v\$(cat ../../VERSION) --files helm/helmfile.yaml --base helmfile --skip-auto-merge --repo https://github.com/favedom-dev/environment-favedom-dev-staging.git
          name: jx-promote
