extends:
  file: ../maven/pipeline.yaml
agent:
  label: jenkins-maven-java11
  image: gcr.io/favedom-dev/jenkins-x/builder-maven-java11:2.1.155-779-jx-patch
  container: maven
pipelineConfig:
  pipelines:
    pullRequest:
      setup:
        steps:
        - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable
      promote:
        replace: true
        steps:
        - dir: charts/preview
          steps:
          - command: make preview
          - command: 'jx preview --app $APP_NAME --namespace=$APP_NAME-$BRANCH_NAME --dir ../..'
