extends:
  file: ../maven-java11-helmfile/pipeline.yaml
env:
  - name: PROMOTE_REPO_URL
    value: https://github.com/favedom-dev/environment-favedom-dev-staging.git

pipelines:
  pullRequest:
    promote:
      steps:
      - sh: |
          chmod -R 777 stackhawk && \
          cd stackhawk && \
          ./setup-hawkscan.sh
        name: setup-stackhawk
      - sh: kubectl apply -f stackhawk-job.yaml
        dir: stackhawk/
        name: run-stackhawk
