extends:
  file: ../maven-java11/pipeline.yaml
env:
  - name: PROMOTE_REPO_URL
    value: https://github.com/favedom-dev/environment-favedom-dev-staging.git
  - name: _JAVA_OPTIONS
    value: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx4g

pipelineConfig:
  pipelines:
    overrides:
    - pipeline: pullRequest
      stage: promote
      containerOptions:
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 4Gi
      # environment:
      # - name: _JAVA_OPTIONS
      #   value: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx4g
      # options:

pipelines:
  pullRequest:
    pipeline:
      promote:
        steps:
        - sh: |
            chmod -R 777 stackhawk && \
            cd stackhawk && \
            ./setup-hawkscan.sh
          name: setup-stackhawk
        - sh: |
            cd ./stackhawk && \
            export REPO_DIR=$(pwd) && \
            export API_KEY=`cat HAWK_API_KEY` && \
            export HAWK_MEM=`cat HAWK_MEM` && \
            echo "==============================" && \
            cat ./stackhawk.yml && \
            echo "REPO_DIR: ${REPO_DIR}" && \
            echo "==============================" && \
            sleep 1200
          name: DEBUG-sleep
          agent:
            image: stackhawk/hawkscan:latest

  release:
    promote:
      replace: true
      steps:
      - dir: charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote to destination Helmfile environment repository
          sh: |
            jx step create pr regex \
              --regex "^\s*- name:\s+$APP_NAME\n\s+version:\s+(?P<version>.*)\$" \
              --version \$(cat ../../VERSION) \
              --files helmfile.yaml \
              --repo $PROMOTE_REPO_URL
          name: jx-promote