extends:
  import: classic
  file: javascript/pipeline.yaml
# agent:
#   image: nodejs14x
#   label: jenkins-nodejs14x
env:
- name: PROMOTE_REPO_URL
  value: https://github.com/favedom-dev/environment-favedom-dev-staging.git
pipelines:
  pullRequest:
    setup:
      steps:
        - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable
        - sh: jx step credential -s npmrc-token-nexus -k .npmrc -f ~/.npmrc --optional=true
    build:
      steps:
      - sh: cd ./apps/api && npm install
        name: api-npm-install
        agent:
          image: ghcr.io/jenkins-x/builder-nodejs14x:2.1.155-778-patch3
      - sh: cd ./apps/api && npm run build
        name: api-build
        agent:
          image: ghcr.io/jenkins-x/builder-nodejs14x:2.1.155-778-patch3
      # - sh: sleep 600
      #   name: DEBUG-sleep
      #   agent:
      #     image: ghcr.io/jenkins-x/builder-nodejs14x:2.1.155-778-patch3
      - sh: export VERSION=$PREVIEW_VERSION && cd ./apps/api && skaffold build -f skaffold.yaml
        name: container-build
        agent:
          image: ghcr.io/jenkins-x/builder-nodejs14x:2.1.155-778-patch3
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: "jx preview --app $APP_NAME --namespace=$APP_NAME-$BRANCH_NAME --dir ../.."
          name: jx-preview

  release:
    setup:
      steps:
        - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable
        - sh: jx step credential -s npmrc-token-nexus -k .npmrc -f ~/.npmrc --optional=true
    build:
      steps:
      - sh: cd ./apps/api && npm install
        name: api-npm-install
        agent:
          image: ghcr.io/jenkins-x/builder-nodejs14x:2.1.155-778-patch3
      - sh: cd ./apps/api && npm run build
        name: api-build
        agent:
          image: ghcr.io/jenkins-x/builder-nodejs14x:2.1.155-778-patch3
      - sh: export VERSION=`cat VERSION` && cd ./apps/api && skaffold build -f skaffold.yaml
        name: container-build
        agent:
          image: ghcr.io/jenkins-x/builder-nodejs14x:2.1.155-778-patch3
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: ./charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --batch-mode --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote to destination Helmfile environment repository
          sh: |
            jx step create pr regex \
              --regex "^\s*- name:\s+$APP_NAME\n\s+version:\s+(?P<version>.*)\$" \
              --version \$(cat ../../VERSION) \
              --files helmfile.yaml \
              --repo $PROMOTE_REPO_URL
          name: jx-promote
