extends:
  file: ../javascript-ui-nginx-helmfile/pipeline.yaml
env:
- name: PROMOTE_REPO_URL
  value: https://github.com/favedom-dev/environment-favedom-dev-staging.git  
pipelines:
  pullRequest:
    build:
      preSteps:
      - command: echo https://peeq-public-assets.joinpeeq.com/${APP_NAME}/${VERSION}/ > DEPLOY_URL
    postBuild:
      steps:
      - command: gsutil -m -q rsync -R dist/${APP_NAME} gs://peeq-public-assets.joinpeeq.com/${APP_NAME}/\${VERSION}
        name: upload-to-gs
  release:
    build:
      preSteps:
      - command: echo https://peeq-public-assets.joinpeeq.com/${APP_NAME}/${VERSION}/ > DEPLOY_URL
    postBuild:
      steps:
      - command: gsutil -m -q rsync -R dist/${APP_NAME} gs://peeq-public-assets.joinpeeq.com/${APP_NAME}/\${VERSION}
        name: upload-to-gs