extends:
  file: ../maven-java11/pipeline.yaml
env:
  - name: PROMOTE_REPO_URL
    value: https://github.com/favedom-dev/environment-favedom-dev-staging.git
pipelines:
  release:
    promote:
      replace: true
      steps:
      - dir: charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote to destination Helmfile environment repository
          sh: |
            jx step create pr regex \
              --regex "^\s*- name:\s+$APP_NAME\n\s+version:\s+(?P<version>.*)\$" \
              --version \$(cat ../../VERSION) \
              --files helmfile.yaml \
              --repo $PROMOTE_REPO_URL 
          name: jx-promote