extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-go
  container: gcr.io/jenkinsxio/builder-go
pipelines:
  release:
    setup:
      steps:
      - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable
    build:
      steps:
        - dir: env
          steps:
            - sh: jx step helm apply
              name: helm-apply

  pullRequest:
    setup:
      steps:
      - sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable
    build:
      steps:
        - dir: env
          steps:
            - sh: jx step helm build
              name: helm-build

