extends:
  import: classic
  file: ../javascript-ui-nginx-helmfile/pipeline.yaml
agent:
  image: nodejs12x
  label: jenkins-nodejs12x
env:
- name: PROMOTE_REPO_URL
  value: https://github.com/favedom-dev/environment-favedom-dev-staging.git
pipelines:
  pullRequest:
    promote:
      steps:
      - sh: |
          chmod -R 777 stackhawk && \
          cd stackhawk && \
          ./setup-hawkscan.sh
        name: setup-stackhawk
      - sh: kubectl replace --force -f stackhawk-job.yaml
        dir: stackhawk/
        name: run-stackhawk

      - sh: ./wait-stackawk.sh
        dir: stackhawk/
        name: wait-stackhawk
